config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes do
  	resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :name, :rating, :comment, presence: true
	validates_length_of :comment, maximum:200
	RATING = [0,1,2,3,4,5]
	validates_inclusion_of :rating, in: RATING

  	belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	validates :name, :stuff, :duration, :prepare_mode, presence:true
	validates_length_of :stuff, maximum: 200
	validates_length_of :prepare_mode, maximum: 300
	validates_numericality_of :calories, greather_than_or_equal_to:0, presence:true
	validates_format_of :poster, allow_blank:true, with:/\w+\.(gif|jpeg|png)\z/i, message:"utiliza apenas os formatos GIF, JPEG ou PNG"
	
	has_many :comments, dependent: :destroy

	KIND = %w{Carnes Aves Peixes Massas Saladas Doces}
	validates_inclusion_of :kind, in: KIND

	def light?
		calories < 100
	end

	def self.created_at
		where('created_at <= ?', Time.now).order('created_at desc')
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_recipe
	
	def index
		@comments = @recipe.comments
	end

	def new
		@comment = @recipe.comments.new
	end

	def create
		@comment = @recipe.comments.new(comment_params)
		if @comment.save
			redirect_to recipe_comments_path(@recipe), notice:"Comentário criado com sucesso!"
		else
			render :new
		end
	end

	private
	def comment_params
		params.require(:comment)
		.permit(:name, :rating, 
			:comment)
	end

	def set_recipe
		@recipe = Recipe.find(params[:recipe_id])
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	def index
		@recipes = Recipe.created_at
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
		@recipe = Recipe.find(params[:id])
		if @recipe.update(recipe_params)
			redirect_to @recipe, notice:"Receita modificada com sucesso!"
		else
			render :edit
		end
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
		if @recipe.save
			redirect_to @recipe, notice:"Receita criada com sucesso!"
		else
			render :new
		end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy
		redirect_to recipes_url, alert:"Receita apagada com sucesso!"
	end

	private
	def recipe_params
		params.require(:recipe)
		.permit(:name, :stuff, 
			:calories, :prepare_mode, :cost,
			:kind, :portion, :duration, :poster)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
	def formata_caloria(recipe)
		if recipe.light?
			content_tag(:strong,"Light (menos de 100 calorias)")
		else
			recipe.calories
		end
	end

	def imagem(recipe)
		if recipe.poster.blank?
			image_tag('sem-imagem.jpg', size:'140')
		else
			image_tag(recipe.poster)
		end
	end
end

app/views/comments/_form.html.erb
<%= form_for([@recipe, @comment]) do |c| %>
	<%= render 'layouts/errors', object:@comment %>
	<p class="form-group">
		<%= c.label :Nome %><br/>
		<%= c.text_field :name, autofocus: true, class:"form-control" %>
	</p>
	<p class="form-group">
		<%= c.label :Estrelas %><br/>
		<%= c.select :rating, Comment::RATING, prompt: "Escolha a quantidade de estrelas", class:"form-control" %>
	</p>
	<p class="form-group">
		<%= c.label :Comentário %><br/>
		<%= c.text_area :comment, placeholder: "Escreva um comentário...", class:"form-control" %>
	</p>
	<p>
		<%= c.submit class:"btn btn-primary" %>
		<%= link_to "Cancelar", root_path, class:"btn btn-default" %>
	</p>
<% end %>

app/views/comments/index.html.erb
<div class="container">
	<% if @recipe.comments.size > 0 %>	
		<div class="jumbotron">
			<ul>
				<% @comments.each do |comment| %>
					<li>
						<p>
							<%= comment.name %> <small class="small_font_rating"> <%= pluralize(comment.rating, 'estrela', 'estrelas') %> </small> <small class="small_font"> - <%= time_ago_in_words(comment.created_at) %> atrás </small>
						</p>
						<p>
							<%= comment.comment %>
						</p>
					</li>
				<% end %>
			</ul>
		</div>
	<% else %>
		<div class="jumbotron">
			<h3>Não existem comentários!</h3>
		</div>
	<% end %>
	
	<%= link_to recipes_path, class:"btn btn-link" do %>
		<i class="glyphicon glyphicon-home"> Receitas</i>
	<% end %>
</div>

app/views/comments/new.html.erb
<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h2>Criando novo Comentário</h2>
		</div>
		<div class="panel-body">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
	<div class="alert alert-warning" role="alert">
		<ul>
			<% object.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="container">
    <div class="alert alert-success alert-dismissible" role="alert">
      <%= flash[:notice] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
  <% elsif flash[:alert] %>
  <div class="container">
    <div class="alert alert-danger alert-dismissible" role="alert">
      <%= flash[:alert] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<p class="text-muted"> Receitas fácil com receitasnet. </p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%=link_to image_tag('receitasnet.jpg', size:'30', alt:'receitasnet'), root_path, class:'navbar-brand' %>
      <%= link_to "Receitasnet", root_path, class:'navbar-brand' %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "Receitas", root_path %> </li>
          
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Receitasnet</title>
    <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<%= render 'layouts/header' %>

    <%= render 'layouts/flash' %>

    <%= yield %>

    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |r| %>
	<%= render 'layouts/errors', object:@recipe %>
	<p class="form-group">
		<%= r.label :Nome %><br>
		<%= r.text_field :name, class:"form-control" %>
	</p>

	<p class="form-group">
		<%= r.label :Ingredientes %><br>
		<%= r.text_area :stuff, cols: 20, rows: 5, class:"form-control" %>
	</p>

	<p class="form-group">
		<%= r.label :Tipo %><br>
		<%= r.select :kind, Recipe::KIND, prompt: "Escolha sua opção:", class:"form-control" %>
	</p>

	<p class="form-group">
		<%= r.label :Calorias %><br>
		<%= r.number_field :calories, class:"form-control" %>
	</p>

	<p class="form-group">
		<%= r.label :Modo_de_preparo %><br>
		<%= r.text_area :prepare_mode, cols: 20, rows: 5, class:"form-control" %>
	</p>

	<p class="form-group">
		<%= r.label :Tempo_de_preparo %><br>
		<%= r.time_select :duration, class:"form-control" %>
	</p>

	<p class="form-group">
		<%= r.label :Porções %><br>
		<%= r.text_field :portion, class:"form-control" %>
	</p>

	<p class="form-group">
		<%= r.label :Custo %><br>
		<%= r.number_field :cost, step: :any, class:"form-control" %>
	</p>

	<p class="form-group">
		<%= r.label :Poster %><br>
		<%= r.text_field :poster, placeholder: ".Gif, .JPG ou .PNG", class:"form-control" %>
	</p>

	<p class="form-group">
		<%= r.submit 'Salvar', class:"btn btn-primary" %>
		<%= link_to 'Cancelar', root_path, class:"btn btn-default" %>
	</p>

<% end %>

app/views/recipes/edit.html.erb
<div class="container">
	<div class="panel panel-default">
  		<div class="panel-heading"><h2>Editando Receita</h2></div>
  		<div class="panel-body">
    		<%= render 'form' %>
  		</div>
	</div>
</div>

app/views/recipes/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">
				<%= pluralize(@recipes.size, "Receita","Receitas") %>
				<small class="nova_receita"> <%= link_to "Nova Receita", new_recipe_path %> </small>
			</h1>
		</div>
	</div>

	<% @recipes.each do |recipe| %>
		<div class="row">
			<div class="col-md-2">
				<%= link_to imagem(recipe), recipe %>
			</div>
			<div class="col-md-7">
				<h3> <%= link_to recipe.name, recipe %> </h3>
				<p>
					<%=truncate(recipe.stuff, length:15, separator:" ") %>
				</p>
				<h4>Calorias:</h4>
				<p>
					<%= formata_caloria(recipe) %>
				</p>
				<h4>Tempo de preparo:</h4>
				<p>
					<%= recipe.duration.to_formatted_s(:time) %>
				</p>
				<h4>Custo:</h4>
				<p>
					<%= number_to_currency(recipe.cost) %>
				</p>
			</div>
		</div>
	<% end %>
</div>

app/views/recipes/new.html.erb
<div class="container">
	<div class="panel panel-default">
  		<div class="panel-heading"><h2>Criando novas Receitas</h2></div>
  		<div class="panel-body">
    		<%= render 'form' %>
  		</div>
	</div>
</div>

app/views/recipes/show.html.erb
<div class="container">
	<div class="jumbotron">
		<article>
			<header>
				<h1> <%= @recipe.name %> </h1>
				<%= imagem(@recipe) %>
			</header>
			<h2>Tipo</h2>
			<p>
				<%= @recipe.kind %>
			</p>
			<h2>Ingredientes</h2>
			<p>
				<%= @recipe.stuff %>
			</p>
			<h2>Calorias</h2>
			<p>
				<%= @recipe.calories %>
			</p>
			<h3>Modo de preparo</h3>
			<p>
				<%= @recipe.prepare_mode %>
			</p>
			<h3>Tempo de Preparo</h3>
			<p>
				<%= @recipe.duration.to_formatted_s(:time) %> min
			</p>
			<h3>Porções</h3>
			<p>
				<%= pluralize(@recipe.portion, 'porção', 'porções') %>
			</p>
			<h3>Custo</h3>
			<p>
				<%= number_to_currency(@recipe.cost) %>
			</p>
		</article>
		<%= link_to pluralize(@recipe.comments.size, 'Comentário', 'Comentários'), recipe_comments_path(@recipe) %>
		<%= link_to "Novo Comentário", new_recipe_comment_path(@recipe), class:"btn btn-primary" %>
	</div>

	<%= link_to recipes_path, class:"btn btn-link" do %>
		<i class="glyphicon glyphicon-home"> Receitas</i>
	<% end %>
	<%= link_to edit_recipe_path(@recipe), class:"btn btn-link" do %>
		<i class="glyphicon glyphicon-edit"> Editar</i>
	<% end %>
	<%= link_to recipe_path(@recipe), method: :delete, data:{confirm:"Deseja deletar essa receita?"}, class:"btn btn-link" do %>
		<i class="glyphicon glyphicon-remove-sign"> Deletar</i>
	<% end %>

</div>